import { google } from 'googleapis';
import fs from 'fs';

const oauth2Client = new google.auth.OAuth2(
  process.env.GOOGLE_CLIENT_ID,
  process.env.GOOGLE_CLIENT_SECRET,
  process.env.GOOGLE_REDIRECT_URI
);

export class GoogleDriveService {
  constructor(accessToken) {
    if (accessToken) {
      oauth2Client.setCredentials({
        access_token: accessToken
      });
    }
  }

  // Ensure folder exists
  async ensureFolder() {
    const drive = google.drive({ version: 'v3', auth: oauth2Client });
    
    try {
      // Check if folder exists
      const response = await drive.files.list({
        q: "name='Patient Summaries' and mimeType='application/vnd.google-apps.folder' and trashed=false",
        fields: 'files(id, name)'
      });

      if (response.data.files.length > 0) {
        return response.data.files[0].id;
      }

      // Create folder
      const folderMetadata = {
        name: 'Patient Summaries',
        mimeType: 'application/vnd.google-apps.folder',
        description: 'Patient consultation summaries generated by Patient-Doctor Summarizer'
      };

      const folder = await drive.files.create({
        resource: folderMetadata,
        fields: 'id'
      });

      return folder.data.id;
    } catch (error) {
      console.error('❌ Google Drive folder error:', error);
      throw error;
    }
  }

  // Upload PDF to Google Drive
  async uploadPDF(filePath, fileName, summaryData) {
    const drive = google.drive({ version: 'v3', auth: oauth2Client });
    
    try {
      const folderId = await this.ensureFolder();

      const fileMetadata = {
        name: fileName,
        parents: [folderId],
        description: `Medical summary for ${summaryData.patientName}`,
        properties: {
          patientName: summaryData.patientName,
          patientAge: summaryData.age,
          patientGender: summaryData.gender,
          diagnosis: summaryData.diagnosis,
          consultationDate: new Date().toISOString(),
          generatedBy: 'Patient-Doctor Summarizer'
        }
      };

      const media = {
        mimeType: 'application/pdf',
        body: fs.createReadStream(filePath)
      };

      const file = await drive.files.create({
        resource: fileMetadata,
        media: media,
        fields: 'id, name, webViewLink, webContentLink'
      });

      console.log('✅ File uploaded to Google Drive:', file.data.id);
      return file.data;
    } catch (error) {
      console.error('❌ Google Drive upload error:', error);
      throw error;
    }
  }

  // Generate PDF content (you can replace this with a proper PDF library)
  generatePDFContent(summaryData) {
    return `
PATIENT MEDICAL SUMMARY
Patient-Doctor Summarizer
Generated: ${new Date().toLocaleDateString()}

================================================================================
PATIENT INFORMATION
================================================================================
Name: ${summaryData.patientName}
Age: ${summaryData.age}
Gender: ${summaryData.gender}

================================================================================
SYMPTOMS & CHIEF COMPLAINT
================================================================================
${summaryData.symptoms}

================================================================================
MEDICAL HISTORY
================================================================================
${summaryData.history || 'No significant medical history noted'}

================================================================================
EXAMINATION FINDINGS
================================================================================
${summaryData.examination || 'No examination findings recorded'}

================================================================================
DIAGNOSIS
================================================================================
${summaryData.diagnosis}

================================================================================
PRESCRIPTION & TREATMENT
================================================================================
${summaryData.prescription || 'No prescription provided'}

================================================================================
FOLLOW-UP INSTRUCTIONS
================================================================================
${summaryData.followUp || 'No specific follow-up instructions'}

--------------------------------------------------------------------------------
This document was automatically generated by Patient-Doctor Summarizer.
Confidential medical information - For authorized personnel only.
--------------------------------------------------------------------------------
    `.trim();
  }
}